openapi: 3.0.3
info:
  title: Mercato (e-commerce API)
  version: 0.0.1
  description: API for managing an online store

components:
  schemas:
    Brand:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 123
          readOnly: true
        name:
          type: string
          minLength: 3
          maxLength: 128
          example: "Xiaomi"
        description:
          type: string
          nullable: true
          example: "Компания Xiaomi производит ..."
        url:
          type: string
          nullable: true
          example: "https://mi.com"

      CreateBrandRequest:
        type: object
        allOf:
          - $ref: '#components/schemas/Brand'
        properties:
          id:
            nullable: false
            readOnly: true
        required:
          - name

      CreateBrandResponse:
        type: object
        allOf:
          - $ref: '#components/schemas/Brand'
        required:
          - id
          - name

      ErrorResponse:
        type: object
        properties:
          timestamp:
            type: string
            format: date-time
          status:
            type: integer
          error:
            type: string
          message:
            type: string
          path:
            type: string
